apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.statefulSet.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    # Allows us to automatically update the stateful set if the config map has
    # changed by using a checksum of the file. This prevents an issue where if 
    # the deployment spec itself didn't change the application keeps running 
    # with the old configuration resulting in an inconsistent deployment.
    checksum/config: {{ include (print $.Template.BasePath "/ConfigMap.yaml") . | sha256sum }}
spec:
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.statefulSet.image.repository }}:{{ .Values.statefulSet.image.tag }}
        imagePullPolicy: {{ .Values.statefulSet.image.pullPolicy }}
        command: ["/bin/node", "start"]
        env:
        - name: "GOSSIP_HOSTS"
          valueFrom:
            configMapKeyRef:
              key: "GOSSIP_HOSTS"
              name: {{ .Release.Name }}
        - name: "GOSSIP_SECRET_KEY"
          valueFrom:
            secretKeyRef:
              key: "GOSSIP_SECRET_KEY"
              name: {{ .Release.Name }}
        - name: "GOSSIP_PORT"
          valueFrom:
            configMapKeyRef:
              key: "GOSSIP_PORT"
              name: {{ .Release.Name }}
        - name: "HTTP_SERVER_PORT"
          valueFrom:
            configMapKeyRef:
              key: "HTTP_SERVER_PORT"
              name: {{ .Release.Name }}
        - name: "HTTP_SERVER_ENABLE_CORS"
          valueFrom:
            configMapKeyRef:
              key: "HTTP_SERVER_ENABLE_CORS"
              name: {{ .Release.Name }}
        - name: "HTTP_CLIENT_TIMEOUT"
          valueFrom:
            configMapKeyRef:
              key: "HTTP_CLIENT_TIMEOUT"
              name: {{ .Release.Name }}