apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  serviceName: {{ .Chart.Name }}
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
        - name: "GOSSIP_HOSTS"
          valueFrom:
            configMapKeyRef:
              key: "GOSSIP_HOSTS"
              name: {{ .Release.Name }}
        - name: "GOSSIP_PORT"
          valueFrom:
            configMapKeyRef:
              key: "GOSSIP_PORT"
              name: {{ .Release.Name }}
        - name: "PORT"
          valueFrom:
            configMapKeyRef:
              key: "PORT"
              name: {{ .Release.Name }}